// Package docs contains the Swagger documentation for the Trending Aggregator API.
//
// This package is auto-generated by swaggo. Run `swag init` from the project root
// to regenerate the swagger.json / swagger.yaml files.
//
//	@title			Trending Aggregator API
//	@version		1.0
//	@description		REST API for GitHub Trending, Starred Repositories, and Product Hunt
//	@termsOfService	http://swagger.io/terms/
//
//	@contact.name		API Support
//	@contact.email		support@trending.local
//
//	@license.name		MIT
//	@license.url		https://opensource.org/licenses/MIT
//
//	@host			localhost:8080
//	@BasePath		/api/v1
//
//	@schemes		http https
package docs

import "github.com/swaggo/swag"

type s struct{}

func (s *s) ReadDoc() string {
	// This function is a placeholder. The actual swagger.json content
	// is generated by `swag init` and embedded at build time.
	return "{}"
}

func init() {
	swag.Register(swag.Name, &s{})
}
