import type { GitHubTrending, GitHubStarred, ProductHunt, DashboardStats } from '@/types';

// ============================================================
// 真实数据 — 2025-05-05 抓取
// 这些数据会被 scripts/fetch-data.js 每天自动更新
// 更新后的数据写入 public/data/*.json
// ============================================================

// GitHub Trending — 今日热门（2025-05-05）
export const mockTrendingRepos: GitHubTrending[] = [
  {
    id: 1,
    repo_name: 'DeepSeek-TUI',
    owner: 'Hmbown',
    full_name: 'Hmbown/DeepSeek-TUI',
    description: 'Coding agent for DeepSeek models that runs in your terminal. Autonomous AI coding assistant with TUI interface.',
    language: 'Rust',
    stars: 6205,
    stars_today: 2389,
    forks: 480,
    period: 'daily',
    fetched_at: '2025-05-05T10:00:00Z',
    url: 'https://github.com/Hmbown/DeepSeek-TUI',
    contributors: 5,
  },
  {
    id: 2,
    repo_name: 'ruflo',
    owner: 'ruvnet',
    full_name: 'ruvnet/ruflo',
    description: 'The leading agent orchestration platform for Claude. Deploy intelligent multi-agent swarms, coordinate autonomous workflows, and build conversational AI systems.',
    language: 'TypeScript',
    stars: 42866,
    stars_today: 2441,
    forks: 4777,
    period: 'daily',
    fetched_at: '2025-05-05T10:00:00Z',
    url: 'https://github.com/ruvnet/ruflo',
    contributors: 12,
  },
  {
    id: 3,
    repo_name: 'dexter',
    owner: 'virattt',
    full_name: 'virattt/dexter',
    description: 'An autonomous agent for deep financial research. AI-powered investment analysis and market intelligence.',
    language: 'TypeScript',
    stars: 23563,
    stars_today: 660,
    forks: 2880,
    period: 'daily',
    fetched_at: '2025-05-05T10:00:00Z',
    url: 'https://github.com/virattt/dexter',
    contributors: 8,
  },
  {
    id: 4,
    repo_name: 'docuseal',
    owner: 'docusealco',
    full_name: 'docusealco/docuseal',
    description: 'Open source DocuSign alternative. Create, fill, and sign digital documents online.',
    language: 'Ruby',
    stars: 13739,
    stars_today: 929,
    forks: 1242,
    period: 'daily',
    fetched_at: '2025-05-05T10:00:00Z',
    url: 'https://github.com/docusealco/docuseal',
    contributors: 6,
  },
  {
    id: 5,
    repo_name: 'vscode-dark-islands',
    owner: 'bwya77',
    full_name: 'bwya77/vscode-dark-islands',
    description: 'VSCode theme based off the easemate IDE and JetBrains islands theme. Dark, clean, modern editor theme.',
    language: 'PowerShell',
    stars: 7663,
    stars_today: 665,
    forks: 231,
    period: 'daily',
    fetched_at: '2025-05-05T10:00:00Z',
    url: 'https://github.com/bwya77/vscode-dark-islands',
    contributors: 3,
  },
  {
    id: 6,
    repo_name: 'context-mode',
    owner: 'mksglu',
    full_name: 'mksglu/context-mode',
    description: 'Context window optimization for AI coding agents. Sandboxes tool output, 98% reduction. 14 platforms.',
    language: 'TypeScript',
    stars: 12801,
    stars_today: 306,
    forks: 883,
    period: 'daily',
    fetched_at: '2025-05-05T10:00:00Z',
    url: 'https://github.com/mksglu/context-mode',
    contributors: 7,
  },
  {
    id: 7,
    repo_name: 'cocoindex',
    owner: 'cocoindex-io',
    full_name: 'cocoindex-io/cocoindex',
    description: 'Incremental engine for long horizon agents. Efficient state management for persistent AI workflows.',
    language: 'Python',
    stars: 8257,
    stars_today: 434,
    forks: 609,
    period: 'daily',
    fetched_at: '2025-05-05T10:00:00Z',
    url: 'https://github.com/cocoindex-io/cocoindex',
    contributors: 6,
  },
  {
    id: 8,
    repo_name: 'agency-agents',
    owner: 'msitarzewski',
    full_name: 'msitarzewski/agency-agents',
    description: 'A complete AI agency at your fingertips — from frontend wizards to community managers, each agent is a specialized expert.',
    language: 'Shell',
    stars: 93309,
    stars_today: 1228,
    forks: 15357,
    period: 'daily',
    fetched_at: '2025-05-05T10:00:00Z',
    url: 'https://github.com/msitarzewski/agency-agents',
    contributors: 15,
  },
  {
    id: 9,
    repo_name: 'coding-interview-university',
    owner: 'jwasham',
    full_name: 'jwasham/coding-interview-university',
    description: 'A complete computer science study plan to become a software engineer.',
    language: '',
    stars: 345604,
    stars_today: 497,
    forks: 82701,
    period: 'daily',
    fetched_at: '2025-05-05T10:00:00Z',
    url: 'https://github.com/jwasham/coding-interview-university',
    contributors: 50,
  },
  {
    id: 10,
    repo_name: 'Scrapling',
    owner: 'D4Vinci',
    full_name: 'D4Vinci/Scrapling',
    description: 'An adaptive Web Scraping framework that handles everything from a single request to a full-scale crawl!',
    language: 'Python',
    stars: 44763,
    stars_today: 915,
    forks: 4123,
    period: 'daily',
    fetched_at: '2025-05-05T10:00:00Z',
    url: 'https://github.com/D4Vinci/Scrapling',
    contributors: 8,
  },
  {
    id: 11,
    repo_name: 'awesome-ai-apps',
    owner: 'Arindam200',
    full_name: 'Arindam200/awesome-ai-apps',
    description: 'A collection of projects showcasing RAG, agents, workflows, and other AI use cases.',
    language: 'Python',
    stars: 11019,
    stars_today: 170,
    forks: 1458,
    period: 'daily',
    fetched_at: '2025-05-05T10:00:00Z',
    url: 'https://github.com/Arindam200/awesome-ai-apps',
    contributors: 15,
  },
  {
    id: 12,
    repo_name: 'Pixelle-Video',
    owner: 'AIDC-AI',
    full_name: 'AIDC-AI/Pixelle-Video',
    description: 'AI fully automated short video engine. Create viral short videos automatically with AI.',
    language: 'Python',
    stars: 11425,
    stars_today: 724,
    forks: 1773,
    period: 'daily',
    fetched_at: '2025-05-05T10:00:00Z',
    url: 'https://github.com/AIDC-AI/Pixelle-Video',
    contributors: 10,
  },
  {
    id: 13,
    repo_name: 'local-deep-research',
    owner: 'LearningCircuit',
    full_name: 'LearningCircuit/local-deep-research',
    description: '~95% on SimpleQA. Supports all local and cloud LLMs. 10+ search engines — arXiv, PubMed, your private documents.',
    language: 'Python',
    stars: 4969,
    stars_today: 200,
    forks: 466,
    period: 'daily',
    fetched_at: '2025-05-05T10:00:00Z',
    url: 'https://github.com/LearningCircuit/local-deep-research',
    contributors: 8,
  },
  {
    id: 14,
    repo_name: 'skills',
    owner: 'browserbase',
    full_name: 'browserbase/skills',
    description: 'Claude Agent SDK with a web browsing tool. Build AI agents that can browse the web.',
    language: 'JavaScript',
    stars: 2296,
    stars_today: 313,
    forks: 148,
    period: 'daily',
    fetched_at: '2025-05-05T10:00:00Z',
    url: 'https://github.com/browserbase/skills',
    contributors: 6,
  },
  {
    id: 15,
    repo_name: 'andrej-karpathy-skills',
    owner: 'forrestchang',
    full_name: 'forrestchang/andrej-karpathy-skills',
    description: 'A single CLAUDE.md file to improve Claude Code behavior, derived from Andrej Karpathy\'s observations.',
    language: '',
    stars: 113166,
    stars_today: 2829,
    forks: 11321,
    period: 'daily',
    fetched_at: '2025-05-05T10:00:00Z',
    url: 'https://github.com/forrestchang/andrej-karpathy-skills',
    contributors: 20,
  },
  {
    id: 16,
    repo_name: 'TabPFN',
    owner: 'PriorLabs',
    full_name: 'PriorLabs/TabPFN',
    description: 'TabPFN: Foundation Model for Tabular Data. Fast and accurate tabular prediction.',
    language: 'Python',
    stars: 6291,
    stars_today: 41,
    forks: 636,
    period: 'daily',
    fetched_at: '2025-05-05T10:00:00Z',
    url: 'https://github.com/PriorLabs/TabPFN',
    contributors: 15,
  },
];

// GitHub Starred — 示例收藏仓库
export const mockStarredRepos: GitHubStarred[] = [
  {
    id: 1,
    repo_name: 'linux',
    owner: 'torvalds',
    full_name: 'torvalds/linux',
    description: 'Linux kernel source tree.',
    language: 'C',
    stars: 189000,
    forks: 51000,
    starred_at: '2025-04-20T08:30:00Z',
    topics: '["kernel", "os"]',
    url: 'https://github.com/torvalds/linux',
    private: false,
  },
  {
    id: 2,
    repo_name: 'neovim',
    owner: 'neovim',
    full_name: 'neovim/neovim',
    description: 'Vim-fork focused on extensibility and usability.',
    language: 'C',
    stars: 89000,
    forks: 5800,
    starred_at: '2025-04-18T14:15:00Z',
    topics: '["editor", "vim"]',
    url: 'https://github.com/neovim/neovim',
    private: false,
  },
  {
    id: 3,
    repo_name: 'rust',
    owner: 'rust-lang',
    full_name: 'rust-lang/rust',
    description: 'Empowering everyone to build reliable and efficient software.',
    language: 'Rust',
    stars: 98000,
    forks: 12800,
    starred_at: '2025-04-15T09:45:00Z',
    topics: '["language", "compiler"]',
    url: 'https://github.com/rust-lang/rust',
    private: false,
  },
  {
    id: 4,
    repo_name: 'tauri',
    owner: 'tauri-apps',
    full_name: 'tauri-apps/tauri',
    description: 'Build smaller, faster, and more secure desktop applications with a web frontend.',
    language: 'Rust',
    stars: 85000,
    forks: 2500,
    starred_at: '2025-04-12T11:20:00Z',
    topics: '["desktop", "webview"]',
    url: 'https://github.com/tauri-apps/tauri',
    private: false,
  },
  {
    id: 5,
    repo_name: 'helix',
    owner: 'helix-editor',
    full_name: 'helix-editor/helix',
    description: 'A post-modern modal text editor.',
    language: 'Rust',
    stars: 34000,
    forks: 1300,
    starred_at: '2025-04-10T16:30:00Z',
    topics: '["editor", "terminal"]',
    url: 'https://github.com/helix-editor/helix',
    private: false,
  },
  {
    id: 6,
    repo_name: 'fish-shell',
    owner: 'fish-shell',
    full_name: 'fish-shell/fish-shell',
    description: 'The user-friendly command line shell.',
    language: 'C++',
    stars: 26000,
    forks: 1900,
    starred_at: '2025-04-08T07:00:00Z',
    topics: '["shell", "terminal"]',
    url: 'https://github.com/fish-shell/fish-shell',
    private: false,
  },
  {
    id: 7,
    repo_name: 'zig',
    owner: 'ziglang',
    full_name: 'ziglang/zig',
    description: 'General-purpose programming language and build system.',
    language: 'Zig',
    stars: 35000,
    forks: 2100,
    starred_at: '2025-04-05T13:10:00Z',
    topics: '["language", "compiler"]',
    url: 'https://github.com/ziglang/zig',
    private: false,
  },
  {
    id: 8,
    repo_name: 'nixpkgs',
    owner: 'NixOS',
    full_name: 'NixOS/nixpkgs',
    description: 'Nix Packages collection.',
    language: 'Nix',
    stars: 21000,
    forks: 16800,
    starred_at: '2025-04-02T19:45:00Z',
    topics: '["nix", "packages"]',
    url: 'https://github.com/NixOS/nixpkgs',
    private: false,
  },
];

// Product Hunt — 今日热门（2025-05-05）
export const mockProductHuntItems: ProductHunt[] = [
  {
    id: 1,
    product_id: 'ph_kilo_code_v7',
    name: 'Kilo Code v7',
    tagline: 'Parallel agents, diff reviewer, and multi-model comparisons',
    description: 'VS Code extension for AI coding with parallel agents, diff reviewer, and multi-model comparisons.',
    url: 'https://www.producthunt.com/products/kilo-code',
    thumbnail: '',
    votes_count: 310,
    comments_count: 58,
    makers: '["Kilo Code Team"]',
    topics: '["Developer Tools", "AI", "VS Code"]',
    day: '2025-05-05',
    featured: true,
  },
  {
    id: 2,
    product_id: 'ph_velo_2',
    name: 'Velo 2.0',
    tagline: 'Turn your voice and screen into shareable videos instantly',
    description: 'Record your voice and screen, instantly turn it into polished, shareable video messages.',
    url: 'https://www.producthunt.com/products/velo',
    thumbnail: '',
    votes_count: 252,
    comments_count: 40,
    makers: '["Velo Team"]',
    topics: '["Productivity", "Video", "Sales"]',
    day: '2025-05-05',
    featured: true,
  },
  {
    id: 3,
    product_id: 'ph_flowstep',
    name: 'Flowstep 1.0',
    tagline: 'AI design engineer — design & ship real UI',
    description: 'AI-powered design tool that lets you design and ship real UI components with natural language.',
    url: 'https://www.producthunt.com/products/flowstep',
    thumbnail: '',
    votes_count: 196,
    comments_count: 37,
    makers: '["Flowstep Team"]',
    topics: '["Developer Tools", "AI", "Design"]',
    day: '2025-05-05',
    featured: true,
  },
  {
    id: 4,
    product_id: 'ph_waydev_agent',
    name: 'Waydev Agent',
    tagline: 'Is your AI spend actually paying off? Prove ROI',
    description: 'Measure and prove the ROI of your AI engineering investments with data-driven insights.',
    url: 'https://www.producthunt.com/products/waydev',
    thumbnail: '',
    votes_count: 165,
    comments_count: 9,
    makers: '["Waydev Team"]',
    topics: '["Developer Tools", "Analytics", "AI"]',
    day: '2025-05-05',
    featured: true,
  },
  {
    id: 5,
    product_id: 'ph_ghostwriter',
    name: 'Ghostwriter',
    tagline: 'Write and publish posts on LinkedIn & X',
    description: 'AI-powered writing assistant for creating and publishing professional social media content.',
    url: 'https://www.producthunt.com/products/ghostwriter',
    thumbnail: '',
    votes_count: 123,
    comments_count: 15,
    makers: '["Ghostwriter Team"]',
    topics: '["Productivity", "Writing", "Social Media"]',
    day: '2025-05-05',
    featured: true,
  },
  {
    id: 6,
    product_id: 'ph_oriane',
    name: 'Oriane',
    tagline: 'The perception layer for Marketers and their AIs',
    description: 'AI-powered marketing perception layer that helps marketers understand and optimize AI interactions.',
    url: 'https://www.producthunt.com/products/oriane',
    thumbnail: '',
    votes_count: 103,
    comments_count: 18,
    makers: '["Oriane Team"]',
    topics: '["Marketing", "AI", "Analytics"]',
    day: '2025-05-05',
    featured: false,
  },
  {
    id: 7,
    product_id: 'ph_intuned_agent',
    name: 'Intuned Agent',
    tagline: 'Production browser automation built and maintained by AI',
    description: 'AI-powered browser automation agent that builds and maintains production-grade web automations.',
    url: 'https://www.producthunt.com/products/intuned',
    thumbnail: '',
    votes_count: 101,
    comments_count: 13,
    makers: '["Intuned Team"]',
    topics: '["Developer Tools", "AI", "Automation"]',
    day: '2025-05-05',
    featured: true,
  },
  {
    id: 8,
    product_id: 'ph_pacebar',
    name: 'PaceBar',
    tagline: 'A quiet pace instrument for your Mac',
    description: 'Minimalist menu bar app for Mac that helps you maintain a healthy work pace.',
    url: 'https://www.producthunt.com/products/pacebar',
    thumbnail: '',
    votes_count: 91,
    comments_count: 2,
    makers: '["PaceBar Team"]',
    topics: '["Mac", "Productivity", "Health"]',
    day: '2025-05-05',
    featured: false,
  },
  {
    id: 9,
    product_id: 'ph_hestus',
    name: 'Hestus',
    tagline: 'Native CAD autocomplete — 2.5x faster, 4x fewer clicks',
    description: 'AI-powered autocomplete for CAD software, dramatically speeding up design workflows.',
    url: 'https://www.producthunt.com/products/hestus',
    thumbnail: '',
    votes_count: 88,
    comments_count: 2,
    makers: '["Hestus Team"]',
    topics: '["Design Tools", "CAD", "AI"]',
    day: '2025-05-05',
    featured: false,
  },
  {
    id: 10,
    product_id: 'ph_wispr_flow',
    name: 'Wispr Flow',
    tagline: 'Dictation that works everywhere — stop typing, start speaking',
    description: 'AI-powered dictation app for Mac. Speak naturally in any app, with tone matching and auto-edits.',
    url: 'https://www.producthunt.com/products/wispr-flow',
    thumbnail: '',
    votes_count: 2290,
    comments_count: 527,
    makers: '["Tanay Kothari", "Sahaj Garg"]',
    topics: '["Productivity", "AI", "Audio"]',
    day: '2025-05-05',
    featured: true,
  },
  {
    id: 11,
    product_id: 'ph_firstwork',
    name: 'Firstwork',
    tagline: 'Agentic AI for frontline hiring and onboarding',
    description: 'AI-powered platform for automating frontline worker hiring and onboarding processes.',
    url: 'https://www.producthunt.com/products/firstwork',
    thumbnail: '',
    votes_count: 86,
    comments_count: 6,
    makers: '["Firstwork Team"]',
    topics: '["HR", "AI", "Hiring"]',
    day: '2025-05-05',
    featured: false,
  },
  {
    id: 12,
    product_id: 'ph_dina',
    name: 'Dina',
    tagline: 'From screen to polished video in minutes',
    description: 'Transform screen recordings into polished, professional videos with AI-powered editing.',
    url: 'https://www.producthunt.com/products/dina',
    thumbnail: '',
    votes_count: 84,
    comments_count: 7,
    makers: '["Dina Team"]',
    topics: '["Video", "AI", "Productivity"]',
    day: '2025-05-05',
    featured: false,
  },
];

export const mockStats: DashboardStats = {
  total_trending: 156,
  total_starred: 42,
  total_producthunt: 89,
  last_fetch_trending: '2025-05-05T10:30:00Z',
  last_fetch_starred: '2025-05-04T16:45:00Z',
  last_fetch_producthunt: '2025-05-05T08:00:00Z',
};

export const mockLanguages = [...new Set(mockTrendingRepos.map((r) => r.language).filter(Boolean))];
